language: Python 
python: 
  - "3.6"
install: 
  - pip install pipenv
  - pipenv install
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE stackoverflow;' -U postgres
script:
  - coverage run --source="." manage.py test
  - coverage report